### ISSUE TITLE
WebDriver获取失败

### ISSUE THREAD

**Issue by xiaobaiweinuli** [jklincn/PaperDownloader#1]
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "gui.py", line 147, in bf_get_driver
  File "driver_helper.py", line 67, in get_driver
  File "driver_helper.py", line 57, in chrome
  File "zipfile.py", line 1267, in __init__
  File "zipfile.py", line 1334, in _RealGetContents
zipfile.BadZipFile: File is not a zip file

**Comment by jklincn** [comment]
你好，可以描述一下浏览器版本吗？我刚刚试了下最新的chrome（版本号117.0.5938.150），是可以自动获取到的
