### ISSUE TITLE
哥，真的很有意义，终于找到了一个能用的了

### ISSUE THREAD

**Issue by Buzeg** [jklincn/PaperDownloader#10]
还有一个问题就是，有没有自动翻页的，如果我需要一个期刊的所有pdf下载，是要一页一页的自己全选吗，一页最多50

**Comment by jklincn** [comment]
谢谢。

刚推送了一个 all-download 分支，不需要勾选，会自动下载所有的检索结果。可以试一下，建议使用高级检索来精确指定文献来源。

知网的防控机制感觉又变严了，图像验证码接口也换了。如果下载过程中碰到知网拦截可以和我反馈。附上具体的下载情况。（间隔时间多少，下载了几篇被拦）

**Comment by Buzeg** [comment]
> 谢谢。
> 
> 刚推送了一个 all-download 分支，不需要勾选，会自动下载所有的检索结果。可以试一下，建议使用高级检索来精确指定文献来源。
> 
> 知网的防控机制感觉又变严了，图像验证码接口也换了。如果下载过程中碰到知网拦截可以和我反馈。附上具体的下载情况。（间隔时间多少，下载了几篇被拦）

非常感谢！！ @jklincn

**Comment by Buzeg** [comment]
> 谢谢。
> 
> 刚推送了一个 all-download 分支，不需要勾选，会自动下载所有的检索结果。可以试一下，建议使用高级检索来精确指定文献来源。
> 
> 知网的防控机制感觉又变严了，图像验证码接口也换了。如果下载过程中碰到知网拦截可以和我反馈。附上具体的下载情况。（间隔时间多少，下载了几篇被拦）

非常感谢！！

**Comment by Buzeg** [comment]
> 谢谢。
> 
> 刚推送了一个 all-download 分支，不需要勾选，会自动下载所有的检索结果。可以试一下，建议使用高级检索来精确指定文献来源。
> 
> 知网的防控机制感觉又变严了，图像验证码接口也换了。如果下载过程中碰到知网拦截可以和我反馈。附上具体的下载情况。（间隔时间多少，下载了几篇被拦）

哥，我想问一下，如果一个期刊有1w篇，算上保守间隔时间的话就是(1+5)s×10000=60000s=6000min=100h吗，中间还有各种意外情况。。 @jklincn

**Comment by jklincn** [comment]
是的，所以说没啥意义。除非我能搞清楚知网的拦截机制，然后绕过它。其实有一个示例，暂时没有时间仔细研究：[zotero-connectors](https://github.com/zotero/zotero-connectors)。不过无论如何，短时间下载 1 万篇论文，你的号肯定会被查，如果是学校账号的话，严重情况下会先把这一个学校的号都封了。

**Comment by yzl256** [comment]
哥，你的all-download分支在哪

**Comment by jklincn** [comment]
@yzl256 分支一直存在啊：https://github.com/jklincn/PaperDownloader/tree/download-all

**Comment by yzl256** [comment]
知网下载10多篇就有验证码了

**Comment by jklincn** [comment]
这个目前无解。知网的验证码我之前做过一个自动识别并处理，但后来知网换接口了，然后原先的识别库也不太好用，目前没精力跟进这一变动。后续本项目可能会使用别的下载方式。

**Comment by Buzeg** [comment]
> 这个目前无解。知网的验证码我之前做过一个自动识别并处理，但后来知网换接口了，然后原先的识别库也不太好用，目前没精力跟进这一变动。后续本项目可能会使用别的下载方式。

如果是用万方会不会好点 @yzl256 @jklincn

**Comment by jklincn** [comment]
> > 这个目前无解。知网的验证码我之前做过一个自动识别并处理，但后来知网换接口了，然后原先的识别库也不太好用，目前没精力跟进这一变动。后续本项目可能会使用别的下载方式。
> 
> 如果是用万方会不会好点 @yzl256 @jklincn

可能，暂未测试

**Comment by yzl256** [comment]
> > 目前这个无解。知网的验证码我先做了一个自动识别并处理，但后来知网换接口了，然后清理的识别库也没什么用，目前没觉察到这个之前的动作。后续本项目可能会使用其他下载方式。
> 
> 如果是用万方会不会好点@yzl256 @jklincn

万方会好很多，但是万方的论文不如知网的多。

**Comment by Buzeg** [comment]
> > > 这个目前无解。知网的验证码我之前做过一个自动识别并处理，但后来知网换接口了，然后原先的识别库也不太好用，目前没精力跟进这一变动。后续本项目可能会使用别的下载方式。
> > 
> > 
> > 如果是用万方会不会好点 @yzl256 @jklincn
> 
> 可能，暂未测试

 你好，运行了之后报错，可以看一看吗 @jklincn 
`=======================================
欢迎使用论文批量下载器 PaperDownloader
当前版本: 2.3.0
=======================================
请选择使用的浏览器:
1: Google Chrome
2: Microsoft Edge

请输入一个整数: 1
使用浏览器: Google Chrome
=======================================
查找可执行文件......成功
=======================================
查找 WebDriver......成功
=======================================
即将打开浏览器......321
=======================================
请登录数据库网站进行内容检索, 在需要下载的论文前面打上勾，完成后输入回车键开始下载
=======================================
程序发生异常，以下为异常信息
=======================================
Traceback (most recent call last):
  File "d:\Implement\CodeData\PaperDownloader-download-all\main.py", line 62, in <module>
    core.download(browse.driver())
                  ^^^^^^^^^^^^^^^
  File "d:\Implement\CodeData\PaperDownloader-download-all\core.py", line 78, in driver
    driver = webdriver.Chrome(options=chrome_options, service=service)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Implement\Anaconda3\envs\scratch\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "D:\Implement\Anaconda3\envs\scratch\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "D:\Implement\Anaconda3\envs\scratch\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "D:\Implement\Anaconda3\envs\scratch\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Implement\Anaconda3\envs\scratch\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "D:\Implement\Anaconda3\envs\scratch\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:16889
from session not created: This version of ChromeDriver only supports Chrome version 129
Current browser version is 131.0.6778.265
Stacktrace:
        GetHandleVerifier [0x00007FF74843B0D5+29557]
        (No symbol) [0x00007FF7483AFA90]
        (No symbol) [0x00007FF74826B56A]
        (No symbol) [0x00007FF7482ADDF7]
        (No symbol) [0x00007FF7482ACE8B]
        (No symbol) [0x00007FF7482A1D25]
        (No symbol) [0x00007FF7482F2F90]
        (No symbol) [0x00007FF7482F2620]
        (No symbol) [0x00007FF7482E6F33]
        (No symbol) [0x00007FF7482B116F]
        (No symbol) [0x00007FF7482B22D1]
        GetHandleVerifier [0x00007FF74876C9AD+3378253]
        GetHandleVerifier [0x00007FF7487B84D7+3688311]
        GetHandleVerifier [0x00007FF7487AD20B+3642539]
        GetHandleVerifier [0x00007FF7484FA6F6+813462]
        (No symbol) [0x00007FF7483BAB9F]
        (No symbol) [0x00007FF7483B6BB4]
        (No symbol) [0x00007FF7483B6D50]
        (No symbol) [0x00007FF7483A5C5F]
        BaseThreadInitThunk [0x00007FFD7075259D+29]
        RtlUserThreadStart [0x00007FFD71FCAF38+40]

版本信息: 
PaperDownloader: 2.3.0
Python: 3.12.0
selenium: 4.27.1
ddddocr: 1.5.6
Google Chrome: 131.0.6778.265
=======================================
在反馈时请务必提供以上所有异常信息，这将有助于问题分析
`

**Comment by Buzeg** [comment]
> > > 这个目前无解。知网的验证码我之前做过一个自动识别并处理，但后来知网换接口了，然后原先的识别库也不太好用，目前没精力跟进这一变动。后续本项目可能会使用别的下载方式。
> > 
> > 
> > 如果是用万方会不会好点 @yzl256 @jklincn
> 
> 可能，暂未测试

好像是浏览器版本太高了，我去看看
