### ISSUE TITLE
个别论文出现TimeoutException报错打断

### ISSUE THREAD

**Issue by wubbxx** [jklincn/PaperDownloader#9]
Traceback (most recent call last):
  File "C:\Users\18237\Desktop\PaperDownloader\main.py", line 62, in <module>
    core.download(browse.driver())
  File "C:\Users\18237\Desktop\PaperDownloader\core.py", line 116, in download
    cnki(driver)
  File "C:\Users\18237\Desktop\PaperDownloader\core.py", line 161, in cnki
    download_button = WebDriverWait(driver, int(config.WaitTime)).until(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\18237\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

版本信息:
PaperDownloader: 2.2.0
Python: 3.12.5
selenium: 4.24.0
ddddocr: 1.5.6
Microsoft Edge: 131.0.2903.99

是不是短时间内下载次数太多，按钮被屏蔽了？如何解决

**Comment by jklincn** [comment]
原来代码中只会下载PDF格式，刚加入了对CAJ的处理。你重新拉一下代码试一下。

**Comment by wubbxx** [comment]
下载次数过多后会被封掉，并出现不同的报错
![image](https://github.com/user-attachments/assets/4b861e4c-dc19-47d3-a035-41a2168ea4f2)


正在接管浏览器控制，请不要操作。
检测到知网检索页面, 开始下载......
滑动验证码错误，自动重试......
滑动验证码错误，自动重试......
滑动验证码错误，自动重试......
程序发生异常，以下为异常信息
=======================================
Traceback (most recent call last):
  File "C:\Users\18237\Desktop\PaperDownloader\main.py", line 62, in <module>
    core.download(browse.driver())
  File "C:\Users\18237\Desktop\PaperDownloader\core.py", line 116, in download
    cnki(driver)
  File "C:\Users\18237\Desktop\PaperDownloader\core.py", line 188, in cnki
    cnki_slide_verify(driver)
  File "C:\Users\18237\Desktop\PaperDownloader\core.py", line 266, in cnki_slide_verify
    background = WebDriverWait(driver, int(config.WaitTime)).until(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\18237\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\18237\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\18237\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 748, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\18237\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\18237\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: MicrosoftEdge=131.0.2903.99)
Stacktrace:
        (No symbol) [0x00007FF723856B05]
        Microsoft::Applications::Events::EventProperty::empty [0x00007FF723B7F474+1437348]
        sqlite3_dbdata_init [0x00007FF723C22DA6+643174]
        (No symbol) [0x00007FF723717657]
        (No symbol) [0x00007FF7237A1CE5]
        (No symbol) [0x00007FF7237B670A]
        (No symbol) [0x00007FF72379BE03]
        (No symbol) [0x00007FF723772984]
        (No symbol) [0x00007FF723771E30]
        (No symbol) [0x00007FF723772571]
        Microsoft::Applications::Events::EventProperty::empty [0x00007FF723B2BB04+1094964]
        (No symbol) [0x00007FF7238932B8]
        Microsoft::Applications::Events::EventProperty::empty [0x00007FF723B2AF43+1091955]
        Microsoft::Applications::Events::EventProperty::empty [0x00007FF723B2AAA9+1090777]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF723930CB1+461569]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF72392C9D4+444452]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF72392CB19+444777]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF723922196+401382]
        BaseThreadInitThunk [0x00007FFD19E0259D+29]
        RtlUserThreadStart [0x00007FFD1B6CAF38+40]

版本信息: 
PaperDownloader: 2.2.0
Python: 3.12.5
selenium: 4.24.0
ddddocr: 1.5.6
Microsoft Edge: 131.0.2903.99

=======================================
正在接管浏览器控制，请不要操作。
检测到知网检索页面, 开始下载......
程序发生异常，以下为异常信息
=======================================
Traceback (most recent call last):
  File "C:\Users\18237\Desktop\PaperDownloader\main.py", line 62, in <module>
    core.download(browse.driver())
  File "C:\Users\18237\Desktop\PaperDownloader\core.py", line 116, in download
    cnki(driver)
  File "C:\Users\18237\Desktop\PaperDownloader\core.py", line 180, in cnki
    WebDriverWait(driver, int(config.WaitTime)).until(
  File "C:\Users\18237\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

版本信息:
PaperDownloader: 2.2.1
Python: 3.12.5
selenium: 4.24.0
ddddocr: 1.5.6
Microsoft Edge: 131.0.2903.99
=======================================

**Comment by wubbxx** [comment]
嗯嗯，不过新代码仿佛自动下载的CAJ，其实我是想下载pdf的

**Comment by jklincn** [comment]
已优先下载PDF，重试一下。另外你之前提的验证码问题，我不确定知网的验证码是否已经修改。反正短时间下载太多的话，知网肯定是封的，建议加大下载间隔时间。

**Comment by wubbxx** [comment]
嗯嗯，被封之后刷新一下cookie就能继续下载了
